language: python
python:
- "3.6"
# setup environment
services: postgresql
env:
- DJANGO_VERSION=1.11.5
# install dependencies
install:
- pip install -r requirements.txt
# run test scripts

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
script:
- python manage.py test 
